"""File stub entity schemas for converter pipeline testing.

Provides file entities (PDF, scanned PDF, PPTX, DOCX) with deterministic
content for testing the text extraction + OCR fallback converters.
"""

from datetime import datetime
from typing import Optional

from pydantic import computed_field

from airweave.platform.entities._airweave_field import AirweaveField
from airweave.platform.entities._base import BaseEntity, FileEntity


class FileStubContainerEntity(BaseEntity):
    """Container entity for file stub entities."""

    container_id: str = AirweaveField(
        ...,
        description="Unique identifier for the file stub container",
        is_entity_id=True,
    )
    container_name: str = AirweaveField(
        ...,
        description="Name of the file stub container",
        is_name=True,
        embeddable=True,
    )
    description: str = AirweaveField(
        default="",
        description="Description of the file stub container",
        embeddable=True,
    )
    created_at: Optional[datetime] = AirweaveField(
        None,
        description="When the container was created",
        is_created_at=True,
    )
    seed: int = AirweaveField(
        default=42,
        description="Random seed used for content generation",
        embeddable=False,
    )
    entity_count: int = AirweaveField(
        default=10,
        description="Total number of file entities in this container",
        embeddable=False,
    )

    @computed_field(return_type=str)
    def web_url(self) -> str:
        """Placeholder URL for the container."""
        return f"file-stub://container/{self.container_id}"


class PdfFileStubEntity(FileEntity):
    """Born-digital PDF file entity with embedded text layer.

    Generated using fpdf2 with real text content that can be extracted
    by PyMuPDF without OCR.
    """

    stub_id: str = AirweaveField(..., description="Unique identifier", is_entity_id=True)
    file_name: str = AirweaveField(..., description="PDF file name", is_name=True, embeddable=True)
    description: str = AirweaveField(
        default="", description="Description of the PDF", embeddable=True
    )
    file_extension: str = AirweaveField(
        default=".pdf", description="File extension", embeddable=True
    )
    author: str = AirweaveField(default="", description="Document author", embeddable=True)
    page_count: int = AirweaveField(default=1, description="Number of pages", embeddable=False)
    created_at: Optional[datetime] = AirweaveField(
        None, description="When the file was created", is_created_at=True
    )
    modified_at: Optional[datetime] = AirweaveField(
        None, description="When the file was last modified", is_updated_at=True
    )
    sequence_number: int = AirweaveField(
        default=0, description="Sequence number for ordering", embeddable=False
    )

    @computed_field(return_type=str)
    def web_url(self) -> str:
        """Return placeholder URL for this PDF entity."""
        return f"file-stub://pdf/{self.stub_id}"


class ScannedPdfFileStubEntity(FileEntity):
    """Image-only (scanned) PDF file entity without a text layer.

    Generated by rendering text onto images with Pillow, then embedding
    those images into a PDF with fpdf2.  Requires OCR to extract content.
    """

    stub_id: str = AirweaveField(..., description="Unique identifier", is_entity_id=True)
    file_name: str = AirweaveField(
        ..., description="Scanned PDF file name", is_name=True, embeddable=True
    )
    description: str = AirweaveField(
        default="", description="Description of the scanned PDF", embeddable=True
    )
    file_extension: str = AirweaveField(
        default=".pdf", description="File extension", embeddable=True
    )
    author: str = AirweaveField(default="", description="Document author", embeddable=True)
    page_count: int = AirweaveField(default=1, description="Number of pages", embeddable=False)
    created_at: Optional[datetime] = AirweaveField(
        None, description="When the file was created", is_created_at=True
    )
    modified_at: Optional[datetime] = AirweaveField(
        None, description="When the file was last modified", is_updated_at=True
    )
    sequence_number: int = AirweaveField(
        default=0, description="Sequence number for ordering", embeddable=False
    )

    @computed_field(return_type=str)
    def web_url(self) -> str:
        """Return placeholder URL for this scanned PDF entity."""
        return f"file-stub://scanned-pdf/{self.stub_id}"


class PptxFileStubEntity(FileEntity):
    """PPTX file entity with extractable slide text.

    Generated using python-pptx with real text content.
    """

    stub_id: str = AirweaveField(..., description="Unique identifier", is_entity_id=True)
    file_name: str = AirweaveField(..., description="PPTX file name", is_name=True, embeddable=True)
    description: str = AirweaveField(
        default="", description="Description of the presentation", embeddable=True
    )
    file_extension: str = AirweaveField(
        default=".pptx", description="File extension", embeddable=True
    )
    author: str = AirweaveField(default="", description="Presentation author", embeddable=True)
    slide_count: int = AirweaveField(default=1, description="Number of slides", embeddable=False)
    created_at: Optional[datetime] = AirweaveField(
        None, description="When the file was created", is_created_at=True
    )
    modified_at: Optional[datetime] = AirweaveField(
        None, description="When the file was last modified", is_updated_at=True
    )
    sequence_number: int = AirweaveField(
        default=0, description="Sequence number for ordering", embeddable=False
    )

    @computed_field(return_type=str)
    def web_url(self) -> str:
        """Return placeholder URL for this PPTX entity."""
        return f"file-stub://pptx/{self.stub_id}"


class DocxFileStubEntity(FileEntity):
    """DOCX file entity with extractable paragraph text.

    Generated using python-docx with real text content.
    """

    stub_id: str = AirweaveField(..., description="Unique identifier", is_entity_id=True)
    file_name: str = AirweaveField(..., description="DOCX file name", is_name=True, embeddable=True)
    description: str = AirweaveField(
        default="", description="Description of the document", embeddable=True
    )
    file_extension: str = AirweaveField(
        default=".docx", description="File extension", embeddable=True
    )
    author: str = AirweaveField(default="", description="Document author", embeddable=True)
    page_count: int = AirweaveField(
        default=1, description="Approximate page count", embeddable=False
    )
    created_at: Optional[datetime] = AirweaveField(
        None, description="When the file was created", is_created_at=True
    )
    modified_at: Optional[datetime] = AirweaveField(
        None, description="When the file was last modified", is_updated_at=True
    )
    sequence_number: int = AirweaveField(
        default=0, description="Sequence number for ordering", embeddable=False
    )

    @computed_field(return_type=str)
    def web_url(self) -> str:
        """Return placeholder URL for this DOCX entity."""
        return f"file-stub://docx/{self.stub_id}"
