"""add_missing_indexes_and_constraints

Revision ID: b788750e60fe
Revises: a1b2c3d4e5f7
Create Date: 2026-02-28 12:22:07.290066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b788750e60fe'
down_revision = 'a1b2c3d4e5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dag_edge')
    op.drop_table('dag_node')
    op.drop_table('sync_dag')
    op.create_index(op.f('ix_access_control_membership_group_id'), 'access_control_membership', ['group_id'], unique=False)
    op.create_index(op.f('ix_access_control_membership_member_id'), 'access_control_membership', ['member_id'], unique=False)
    op.create_index(op.f('ix_access_control_membership_organization_id'), 'access_control_membership', ['organization_id'], unique=False)
    op.drop_constraint(op.f('access_control_membership_organization_id_fkey'), 'access_control_membership', type_='foreignkey')
    op.create_foreign_key(None, 'access_control_membership', 'organization', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_collection_vdb_metadata_id', 'collection', ['vector_db_deployment_metadata_id'], unique=False)
    op.create_index('idx_connection_integration_credential_id', 'connection', ['integration_credential_id'], unique=False)
    op.create_index('idx_connection_organization_id', 'connection', ['organization_id'], unique=False)
    op.create_index('idx_connection_init_session_expires_at', 'connection_init_session', ['expires_at'], unique=False)
    op.drop_index(op.f('idx_entity_count_sync_def'), table_name='entity_count')
    op.drop_index('ix_search_queries_query_text', table_name='search_queries')
    op.create_index('idx_entity_relation_from', 'entity_relation', ['from_entity_definition_id'], unique=False)
    op.create_index('idx_entity_relation_to', 'entity_relation', ['to_entity_definition_id'], unique=False)
    op.create_unique_constraint('uq_entity_relation', 'entity_relation', ['from_entity_definition_id', 'to_entity_definition_id', 'name', 'organization_id'])
    op.create_index('idx_organization_auth0_org_id', 'organization', ['auth0_org_id'], unique=False)
    op.create_index('idx_redirect_session_expires_at', 'redirect_session', ['expires_at'], unique=False)
    op.create_index('idx_source_connection_collection_id', 'source_connection', ['readable_collection_id'], unique=False)
    op.create_index('idx_source_connection_connection_id', 'source_connection', ['connection_id'], unique=False)
    op.create_index('idx_source_connection_sync_id', 'source_connection', ['sync_id'], unique=False)
    op.drop_index(op.f('ix_source_rate_limits_lookup'), table_name='source_rate_limits')
    op.create_index('idx_sync_connection_connection_id', 'sync_connection', ['connection_id'], unique=False)
    op.create_index('idx_sync_connection_sync_id', 'sync_connection', ['sync_id'], unique=False)
    op.create_unique_constraint('uq_sync_connection', 'sync_connection', ['sync_id', 'connection_id'])
    op.create_index('idx_sync_job_sync_id', 'sync_job', ['sync_id'], unique=False)
    op.drop_index(op.f('ix_user_organization_organization_id'), table_name='user_organization')
    op.create_unique_constraint('uq_user_organization', 'user_organization', ['user_id', 'organization_id'])
    op.create_table_comment(
        'vector_db_deployment_metadata',
        'Singleton table — exactly one row, enforced by CHECK(singleton)',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'vector_db_deployment_metadata',
        existing_comment='Singleton table — exactly one row, enforced by CHECK(singleton)',
        schema=None
    )
    op.drop_constraint('uq_user_organization', 'user_organization', type_='unique')
    op.create_index(op.f('ix_user_organization_organization_id'), 'user_organization', ['organization_id'], unique=False)
    op.drop_index('idx_sync_job_sync_id', table_name='sync_job')
    op.drop_constraint('uq_sync_connection', 'sync_connection', type_='unique')
    op.drop_index('idx_sync_connection_sync_id', table_name='sync_connection')
    op.drop_index('idx_sync_connection_connection_id', table_name='sync_connection')
    op.create_index(op.f('ix_source_rate_limits_lookup'), 'source_rate_limits', ['organization_id', 'source_short_name'], unique=False)
    op.drop_index('idx_source_connection_sync_id', table_name='source_connection')
    op.drop_index('idx_source_connection_connection_id', table_name='source_connection')
    op.drop_index('idx_source_connection_collection_id', table_name='source_connection')
    op.drop_index('idx_redirect_session_expires_at', table_name='redirect_session')
    op.drop_index('idx_organization_auth0_org_id', table_name='organization')
    op.drop_constraint('uq_entity_relation', 'entity_relation', type_='unique')
    op.drop_index('idx_entity_relation_to', table_name='entity_relation')
    op.drop_index('idx_entity_relation_from', table_name='entity_relation')
    op.create_index(op.f('idx_entity_count_sync_def'), 'entity_count', ['sync_id', 'entity_definition_id'], unique=False)
    op.create_index('ix_search_queries_query_text', 'search_queries', ['query_text'], unique=False)
    op.drop_index('idx_connection_init_session_expires_at', table_name='connection_init_session')
    op.drop_index('idx_connection_organization_id', table_name='connection')
    op.drop_index('idx_connection_integration_credential_id', table_name='connection')
    op.drop_index('idx_collection_vdb_metadata_id', table_name='collection')
    op.drop_constraint(None, 'access_control_membership', type_='foreignkey')
    op.create_foreign_key(op.f('access_control_membership_organization_id_fkey'), 'access_control_membership', 'organization', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_access_control_membership_organization_id'), table_name='access_control_membership')
    op.drop_index(op.f('ix_access_control_membership_member_id'), table_name='access_control_membership')
    op.drop_index(op.f('ix_access_control_membership_group_id'), table_name='access_control_membership')
    op.create_table('sync_dag',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sync_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modified_by_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('sync_dag_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_id'], ['sync.id'], name=op.f('sync_dag_sync_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_dag_pkey')),
    sa.UniqueConstraint('sync_id', name=op.f('uq_sync_dag_def_sync_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('dag_node',
    sa.Column('dag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('connection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('entity_definition_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('transformer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modified_by_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], name=op.f('dag_node_connection_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dag_id'], ['sync_dag.id'], name=op.f('dag_node_dag_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_definition_id'], ['entity_definition.id'], name=op.f('dag_node_entity_definition_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('dag_node_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transformer_id'], ['transformer.id'], name=op.f('dag_node_transformer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dag_node_pkey'))
    )
    op.create_table('dag_edge',
    sa.Column('dag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('from_node_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('to_node_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modified_by_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dag_id'], ['sync_dag.id'], name=op.f('dag_edge_dag_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_node_id'], ['dag_node.id'], name=op.f('dag_edge_from_node_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('dag_edge_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['dag_node.id'], name=op.f('dag_edge_to_node_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dag_edge_pkey')),
    sa.UniqueConstraint('dag_id', 'from_node_id', 'to_node_id', name=op.f('uq_dag_edge_from_to'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
